/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GaugeController } from "./GaugeController";
export * as factories from "./factories";
export { GaugeController__factory } from "./factories/GaugeController__factory";
